### ISSUE TITLE
dependencies issue

### ISSUE THREAD

**Issue by ShivamKR12** [XenonCoder/PyCraft#53]
please provide the name and versions of every used by this repo, since i am having a lot of troble find the right vresion for it to run

**Comment by ShivamKR12** [comment]
PS C:\Users\Shivam\Desktop\new\TerraCraft-master> python -m venv venv
>> 
PS C:\Users\Shivam\Desktop\new\TerraCraft-master> cmd
Microsoft Windows [Version 10.0.22631.4602]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Shivam\Desktop\new\TerraCraft-master>.\venv\Scripts\activate

(venv) C:\Users\Shivam\Desktop\new\TerraCraft-master>pip install pyglet==1.5.27
Collecting pyglet==1.5.27
  Using cached pyglet-1.5.27-py3-none-any.whl.metadata (7.6 kB)
Using cached pyglet-1.5.27-py3-none-any.whl (1.1 MB)
Installing collected packages: pyglet
Successfully installed pyglet-1.5.27

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) C:\Users\Shivam\Desktop\new\TerraCraft-master>
(venv) C:\Users\Shivam\Desktop\new\TerraCraft-master>python main.py
C:\Users\Shivam\Desktop\new\TerraCraft-master\main.py:4: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\graphics.py:4: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\config.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\scenemanager.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\savemanager.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\scenes.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\blocks.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\utilities.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\genworld.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\noise.py:4: SyntaxWarning: invalid escape sequence '\ '
  """
C:\Users\Shivam\Desktop\new\TerraCraft-master\game\world.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\main.py", line 65, in <module>
    main()
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\main.py", line 56, in main
    scene_manager = SceneManager(window=window)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\game\scenemanager.py", line 55, in __init__
    self.add_scene(MenuScene(self.window))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\game\scenes.py", line 124, in __init__
    self.start_label = pyglet.text.Label('Select save & press Enter to start', font_size=25,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\__init__.py", line 469, in __init__
    super(Label, self).__init__(document, x, y, width, height,
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\__init__.py", line 268, in __init__
    super(DocumentLabel, self).__init__(document,
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 858, in __init__
    self.document = document
    ^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 887, in document
    self._init_document()
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1336, in _init_document
    self._update()
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1247, in _update
    lines = self._get_lines()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1224, in _get_lines
    glyphs = self._get_glyphs()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1384, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\font\base.py", line 401, in get_glyphs
    glyph_renderer = self.glyph_renderer_class(self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\font\win32.py", line 100, in __init__
    self._create_bitmap(width, height)
  File "C:\Users\Shivam\Desktop\new\TerraCraft-master\venv\Lib\site-packages\pyglet\font\win32.py", line 324, in _create_bitmap
    gdiplus.GdipCreateBitmapFromScan0(width, height, width * 4,
ctypes.ArgumentError: argument 5: TypeError: expected LP_c_ubyte instance instead of c_byte_Array_3520

(venv) C:\Users\Shivam\Desktop\new\TerraCraft-master>

**Comment by ShivamKR12** [comment]
@XenonLab-Studio

**Comment by ShivamKR12** [comment]
please help
